"""
DARX Site Generator - Cloud Run Service

Generates production-ready Next.js websites with Builder.io integration.
"""

import os
import json
import time
import functions_framework
from flask import Request, jsonify
from typing import Dict, Any
from darx.clients.vertex_ai import generate_site_code
from darx.clients.github import create_github_repo, push_to_github
from darx.clients.vercel import deploy_to_vercel
from darx.clients.builder_io import create_space, register_components, create_initial_page
from darx.clients.gcp import store_backup, log_generation

# Configuration
PROJECT_ID = os.getenv('GCP_PROJECT', 'sylvan-journey-474401-f9')
LOCATION = os.getenv('GCP_LOCATION', 'us-central1')
GITHUB_ORG = os.getenv('GITHUB_ORG', 'darx-sites')


@functions_framework.http
def generate_site(request: Request):
    """
    Main HTTP endpoint for website generation.

    Request body:
    {
        "project_name": "acme-corp",
        "client_info": {...},
        "requirements": "Build a landing page...",
        "industry": "real-estate",
        "features": ["spline-3d", "hubspot-form"]
    }

    Returns:
    {
        "success": true,
        "staging_url": "https://staging.acme-corp.darx.site",
        "github_repo": "https://github.com/darx-sites/acme-corp",
        "builder_io_project": "acme-corp",
        "components_registered": [...]
    }
    """

    # Handle CORS preflight
    if request.method == 'OPTIONS':
        return _cors_response()

    # Parse request
    try:
        data = request.get_json()
        if not data:
            return jsonify({'error': 'No JSON data provided'}), 400

        project_name = data.get('project_name')
        client_info = data.get('client_info', {})
        requirements = data.get('requirements')
        industry = data.get('industry', 'general')
        features = data.get('features', [])

        if not project_name or not requirements:
            return jsonify({
                'error': 'Missing required fields: project_name, requirements'
            }), 400

    except Exception as e:
        return jsonify({'error': f'Invalid request: {str(e)}'}), 400

    print(f"\n🚀 Starting generation for: {project_name}")
    print(f"   Industry: {industry}")
    print(f"   Features: {', '.join(features)}")

    start_time = time.time()

    try:
        # Step 1: Generate code with Claude
        print("\n📝 Generating code with Claude Sonnet 4.5...")
        generation_result = generate_site_code(
            project_name=project_name,
            requirements=requirements,
            industry=industry,
            features=features,
            client_info=client_info
        )

        if not generation_result.get('success'):
            raise Exception(generation_result.get('error', 'Code generation failed'))

        files = generation_result['files']
        components = generation_result['components']

        print(f"   ✅ Generated {len(files)} files")
        print(f"   ✅ Registered {len(components)} components")

        # Step 2: Create GitHub repository
        print(f"\n📦 Creating GitHub repository: {GITHUB_ORG}/{project_name}")
        github_result = create_github_repo(
            org=GITHUB_ORG,
            repo_name=project_name,
            description=f"Website for {client_info.get('company_name', project_name)}"
        )

        if not github_result.get('success'):
            raise Exception(github_result.get('error', 'GitHub repo creation failed'))

        repo_url = github_result['repo_url']
        print(f"   ✅ Repository created: {repo_url}")

        # Step 3: Push code to GitHub
        print("\n⬆️  Pushing code to GitHub...")
        push_result = push_to_github(
            org=GITHUB_ORG,
            repo_name=project_name,
            files=files,
            commit_message=f"Initial commit - Generated by DARX\n\nIndustry: {industry}\nComponents: {len(components)}"
        )

        if not push_result.get('success'):
            raise Exception(push_result.get('error', 'GitHub push failed'))

        print("   ✅ Code pushed to GitHub")

        # Step 4: Deploy to Vercel
        print("\n🚀 Deploying to Vercel...")
        vercel_result = deploy_to_vercel(
            project_name=project_name,
            github_repo=f"{GITHUB_ORG}/{project_name}",
            env_vars={
                'NEXT_PUBLIC_BUILDER_API_KEY': os.getenv('BUILDER_IO_PUBLIC_KEY'),
                'BUILDER_PRIVATE_KEY': os.getenv('BUILDER_IO_PRIVATE_KEY'),
            }
        )

        if not vercel_result.get('success'):
            raise Exception(vercel_result.get('error', 'Vercel deployment failed'))

        staging_url = vercel_result['staging_url']
        print(f"   ✅ Deployed to: {staging_url}")

        # Step 5: Create Builder.io space and register components
        print("\n🎨 Setting up Builder.io visual editor...")
        builder_result = create_space(
            project_name=project_name,
            company_name=client_info.get('company_name')
        )

        builder_space_id = project_name  # Default to project_name
        if builder_result.get('success'):
            builder_space_id = builder_result.get('space_id', project_name)
            print(f"   ✅ Builder.io space created: {builder_space_id}")

            # Register custom components
            if components:
                register_result = register_components(
                    space_id=builder_space_id,
                    components=components,
                    staging_url=staging_url
                )
                if register_result.get('success'):
                    print(f"   ✅ Registered {register_result.get('registered', 0)} components")

            # Create initial page entry
            create_initial_page(
                space_id=builder_space_id,
                project_name=project_name
            )
        else:
            print(f"   ⚠️  Builder.io setup skipped: {builder_result.get('error')}")
            print(f"   ℹ️  Site will still work, but visual editing won't be available")

        # Step 6: Store backup in GCS
        print("\n💾 Storing backup in Cloud Storage...")
        backup_result = store_backup(
            project_name=project_name,
            files=files,
            metadata={
                'industry': industry,
                'features': features,
                'components': components,
                'generation_time': time.time() - start_time
            }
        )

        # Step 7: Log generation metrics
        generation_time = time.time() - start_time
        log_generation(
            project_name=project_name,
            industry=industry,
            components=len(components),
            files=len(files),
            generation_time=generation_time,
            success=True
        )

        print(f"\n✨ Generation complete! ({generation_time:.2f}s)")

        # Return success response
        response = {
            'success': True,
            'project_name': project_name,
            'staging_url': staging_url,
            'github_repo': repo_url,
            'builder_io_project': builder_space_id,
            'builder_io_url': f'https://builder.io/content?space={builder_space_id}',
            'components_registered': components,
            'generation_time': generation_time,
            'files_generated': len(files)
        }

        return jsonify(response), 200

    except Exception as e:
        error_msg = str(e)
        print(f"\n❌ Generation failed: {error_msg}")

        # Log failure
        log_generation(
            project_name=project_name,
            industry=industry,
            components=0,
            files=0,
            generation_time=time.time() - start_time,
            success=False,
            error=error_msg
        )

        return jsonify({
            'success': False,
            'error': error_msg,
            'project_name': project_name
        }), 500


@functions_framework.http
def health(request: Request):
    """Health check endpoint"""
    return jsonify({'status': 'healthy', 'service': 'darx-site-generator'}), 200


def _cors_response():
    """Handle CORS preflight requests"""
    headers = {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type',
        'Access-Control-Max-Age': '3600'
    }
    return ('', 204, headers)
